fix: hardening pdf processing by disabling scripting in pdf viewer
owncloud/files_pdfviewer pull request #331
Opened 2024-01-11 09:59 UTC by DeepDiver1975

2024-01-11 09:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/files_pdfviewer?pullRequest=331) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/files_pdfviewer?pullRequest=331) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/files_pdfviewer?pullRequest=331) it.</sub>

2024-01-11 10:08 UTC, JanAckermann approved these changes

2024-01-11 11:40 UTC, JanAckermann commented on js/workersrc.js
> +		PDFViewerApplicationOptions.set('enableScripting', head.getAttribute('data-enableScriting'));
Do we need to cast the string ?

2024-01-11 11:43 UTC, pako81 commented on js/workersrc.js
> +		PDFViewerApplicationOptions.set('enableScripting', head.getAttribute('data-enableScriting'));
`data-enableScriting`--> `data-enableScripting`

2024-01-11 11:43 UTC, pako81 commented on templates/viewer.php
> +	  data-enableScriting="<?php p($enableScripting ? 'true' : 'false') ?>"
`data-enableScriting`--> `data-enableScripting`

2024-01-11 11:44 UTC, JanAckermann requested changes
Fix typo, check if bool cast is required

2024-01-11 11:54 UTC, DeepDiver1975 commented on js/workersrc.js
> +		PDFViewerApplicationOptions.set('enableScripting', head.getAttribute('data-enableScriting'));
:see_no_evil:

2024-01-11 11:55 UTC, JanAckermann approved these changes

2024-01-11 11:59 UTC, pako81 approved these changes

2024-01-15 10:44 UTC, merged

2024-02-06 15:27 UTC, empty00 commented
@DeepDiver1975 could you please replay the report in HackerOne